=== sameer05515/MyTestPrograms/oneTouch/dtd/links1.1.dtd
<!--
	* 	zero or more occurence
	?	zero or one occurance
	
	Introduction to DTD

by Jan Egil Refsnes
Originally published at http://www.xmlfiles.com/dtd/
Minor revision made by Junghoo "John" Cho for the CS188 class at UCLA

The purpose of a DTD is to define the legal building blocks of an XML document. It defines the document structure with a list of legal elements. A DTD can be declared inline in your XML document, or as an external reference.

Internal DTD

This is an XML document with a Document Type Definition:

<?xml version="1.0"?>
<!DOCTYPE note [
  <!ELEMENT note    (to,from,heading,body)>
  <!ELEMENT to      (#PCDATA)>
  <!ELEMENT from    (#PCDATA)>
  <!ELEMENT heading (#PCDATA)>
  <!ELEMENT body    (#PCDATA)>
]>

<note>
  <to>Tove</to>
  <from>Jani</from>
  <heading>Reminder</heading>
  <body>Don't forget me this weekend</body>
</note>
Like the above example, if the DTD is to be included in your XML source file, it should be wrapped in a DOCTYPE definition with the following syntax:

<!DOCTYPE root-element [element-declarations]>
In the above example, the DTD is interpreted like this:
!ELEMENT note (in line 2) defines the element "note" as having four elements: "to,from,heading,body".
!ELEMENT to (in line 3) defines the "to" element  to be of the type "CDATA".
!ELEMENT from (in line 4) defines the "from" element to be of the type "CDATA"
and so on.....

External DTD

This is the same XML document with an external DTD:

<?xml version="1.0"?>

<!DOCTYPE note SYSTEM "note.dtd">
<note>
   <to>Tove</to>
   <from>Jani</from>
   <heading>Reminder</heading>
   <body>Don't forget me this weekend!</body>
</note> 
This is a copy of the file "note.dtd" containing the Document Type Definition:

<?xml version="1.0"?>
<!ELEMENT note (to,from,heading,body)>
<!ELEMENT to (#PCDATA)>
<!ELEMENT from (#PCDATA)>
<!ELEMENT heading (#PCDATA)>
<!ELEMENT body (#PCDATA)>

The building blocks of XML documents

XML documents (and HTML documents) are made up by the following building blocks:

Elements, Tags, Attributes, Entities, #PCDATA, and CDATA

We now briefly explain each of the building blocks:

Elements

Elements are the main building blocks of both XML and HTML documents.

Examples of HTML elements are "body" and "table". Examples of XML elements could be "note" and "message". Elements can contain text, other elements, or be empty. Examples of empty HTML elements are "hr", "br" and "img".

Tags

Tags are used to markup elements.

A starting tag like <element_name> mark up the beginning of an element, and an ending tag like </element_name>  mark up the end of  an element.

Examples:
A body element: <body>body text in between</body>.
A message element: <message>some message in between</message>

Attributes

Attributes provide extra information about elements.

Attributes are placed inside the start tag of an element. Attributes come in name/value pairs. The following "img" element has an additional information about a source file:

<img src="computer.gif" />
The name of the element is "img". The name of the attribute is "src". The value of the attribute is "computer.gif". Since the element itself is empty it is closed by a " /".

#PCDATA

#PCDATA means parsed character data.

Think of character data as the text found between the start tag and the end tag of an XML element.

#PCDATA is text that will be parsed by a parser. Tags inside the text will be treated as markup and entities will be expanded. 

CDATA

CDATA also means character data.

CDATA is text that will NOT be parsed by a parser. Tags inside the text will NOT be treated as markup and entities will not be expanded.

Entities

Entities as variables used to define common text. Entity references are references to entities.

Most of you will known the HTML entity reference: "&nbsp;"  that is used to insert an extra space in an HTML document. Entities are expanded when a document is parsed by an XML parser.

The following entities are predefined in XML:

Entity References	Character
&lt;	<
&gt;	>
&amp;	&
&quot;	"
&apos;	'
 
Declaring an Element

In the DTD, XML elements are declared with an element declaration. An element declaration has the following syntax:

<!ELEMENT element-name (element-content)>

Empty elements

Empty elements are declared with the keyword EMPTY inside the parentheses:

<!ELEMENT element-name (EMPTY)>

example:
<!ELEMENT img (EMPTY)>

Elements with data

Elements with data are declared with the data type inside parentheses:

<!ELEMENT element-name (#PCDATA)>
or
<!ELEMENT element-name (#PCDATA)>
or
<!ELEMENT element-name (ANY)>
example:
<!ELEMENT note (#PCDATA)>

CDATA means the element contains character data that is not supposed to be parsed by a parser.
#PCDATA means that the element contains data that IS going to be parsed by a parser.
The keyword ANY declares an element with any content.
If a #PCDATA section contains elements, these elements must also be declared.

Elements with children (sequences)

Elements with one or more children are defined with the name of the children elements inside the parentheses:

<!ELEMENT element-name (child-element-name)>
or
<!ELEMENT element-name (child-element-name,child-element-name,.....)>
example:
<!ELEMENT note (to,from,heading,body)>

When children are declared in a sequence separated by commas, the children must appear in the same sequence in the document. In a full declaration, the children must also be declared, and the children can also have children. The full declaration of the note document will be:
<!ELEMENT note (to,from,heading,body)>
<!ELEMENT to      (#PCDATA)>
<!ELEMENT from    (#PCDATA)>
<!ELEMENT heading (#PCDATA)>
<!ELEMENT body    (#PCDATA)>

Declaring only one occurrence of the same element 

<!ELEMENT element-name (child-name)>
example
<!ELEMENT note (message)>
The example declaration above declares that the child element message can only occur one time inside the note element.

Declaring minimum one occurrence of the same element

<!ELEMENT element-name (child-name+)>
example
<!ELEMENT note (message+)>
The + sign in the example above declares that the child element message must occur one or more times inside the note element.

Declaring zero or more occurrences of the same element 

<!ELEMENT element-name (child-name*)>
example
<!ELEMENT note (message*)>
The * sign in the example above declares that the child element message can occur zero or more times inside the note element.

Declaring zero or one occurrences of the same element 

<!ELEMENT element-name (child-name?)>
example
<!ELEMENT note (message?)>
The ? sign in the example above declares that the child element message can occur zero or one times inside the note element.

Declaring mixed content

example
<!ELEMENT note (to+,from,header,message*,#PCDATA)>
The example above declares that the element note must contain at least one to child element, exactly one from child element, exactly one header, zero or more message, and some other parsed character data as well. Puh!

Declaring Attributes

In the DTD, XML element attributes are declared with an ATTLIST declaration. An attribute declaration has the following syntax:

<!ATTLIST element-name attribute-name attribute-type default-value>

As you can see from the syntax above, the ATTLIST declaration defines the element which can have the attribute, the name of the attribute, the type of the attribute, and the default attribute value.
The attribute-type can have the following values:

Value	Explanation
CDATA
The value is character data
(eval|eval|..)
The value must be an enumerated value
ID
The value is an unique id 
IDREF
The value is the id of another element
IDREFS
The value is a list of other ids
NMTOKEN
The value is a valid XML name
NMTOKENS
The value is a list of valid XML names
ENTITY
The value is an entity 
ENTITIES
The value is a list of entities
NOTATION
The value is a name of a notation
xml:
The value is predefined
The attribute-default-value can have the following values:

Value	Explanation
value
The attribute has the default value "value"
#REQUIRED
The attribute value must be included in the element
#IMPLIED
The attribute is optional and does not have to be included
#FIXED value
The attribute value is fixed

Attribute declaration example

DTD example:
<!ELEMENT square (EMPTY)>
<!ATTLIST square width CDATA "0">

XML example:
<square width="100"></square>

In the above example the element square is defined to be an empty element with the attributes width of  type CDATA. The width attribute has a default value of 0. 
Default attribute value

Syntax:
<!ATTLIST element-name attribute-name CDATA "default-value">

DTD example:
<!ATTLIST payment type CDATA "check">

XML example:
<payment type="check">

Specifying a default value for an attribute, assures that the attribute will get a value even if the author of the XML document didn't include it.
Implied attribute

Syntax:
<!ATTLIST element-name attribute-name attribute-type #IMPLIED>
DTD example:
<!ATTLIST contact fax CDATA #IMPLIED>

XML example:
<contact fax="555-667788">

Use an implied attribute if you don't want to force the author to include an attribute and you don't have an option for a default value either. 
Required attribute

Syntax:
<!ATTLIST element-name attribute_name attribute-type #REQUIRED>
DTD example:
<!ATTLIST person number CDATA #REQUIRED>

XML example:
<person number="5677">

Use a required attribute if you don't have an option for a default value, but still want to force the attribute to be present.
Fixed attribute value

Syntax:
<!ATTLIST element-name attribute-name attribute-type #FIXED "value">
DTD example:
<!ATTLIST sender company CDATA #FIXED "Microsoft">


XML example:
<sender company="Microsoft">

Use a fixed attribute value when you want an attribute to have a fixed value without allowing the author to change it. If an author includes another value, the XML parser will return an error.
Enumerated attribute values

Syntax:
<!ATTLIST element-name attribute-name (eval|eval|..) default-value>
DTD example:
<!ATTLIST payment type (check|cash) "cash">

XML example:
<payment type="check">
or
<payment type="cash">

Use enumerated attribute values when you want the attribute values to be one of a fixed set of legal values.
Entities

Entities are "shortcuts" to common text and can be defined internally or externally.
Internal Entity Declaration

Syntax: 
<!ENTITY entity-name "entity-value">

DTD Example:
<!ENTITY writer "Jan Egil Refsnes.">
<!ENTITY copyright "Copyright XML101.">
XML example:
<author>&writer;&copyright;</author>
 
External Entity Declaration

Syntax: 
<!ENTITY entity-name SYSTEM "URI/URL">

DTD Example:
<!ENTITY writer    SYSTEM "http://www.xml101.com/entities/entities.xml">
<!ENTITY copyright SYSTEM "http://www.xml101.com/entities/entities.dtd">
XML example:
<author>&writer;&copyright;</author>
	
-->

<!ELEMENT root (link-group*)>
<!ELEMENT link-group (link*)>
<!ELEMENT link (url)>
<!ATTLIST link-group name CDATA #REQUIRED>

<!ELEMENT url (#PCDATA)>
<!--<!ELEMENT root (person-relation-list*)>-->

=== sameer05515/MyTestPrograms/oneTouch/xml/links1.1.xml
<?xml version="1.0"?>
<!DOCTYPE root SYSTEM "http://127.0.0.1:8080/hibTutorial/dtd/links1.1.dtd">


<root>
	<link-group name="hibernate tutorial">
		<link><url><![CDATA[http://127.0.0.1:8080/hibTutorial/hibernate-release-4.3.6.Final/documentation/quickstart/en-US/html_single/index.html]]> </url></link>
		<link><url><![CDATA[http://127.0.0.1:8080/hibTutorial/hibernate-release-4.3.6.Final/documentation/quickstart/en-US/html/index.html]]> </url></link>
		<link><url><![CDATA[http://127.0.0.1:8080/hibTutorial/hibernate-release-4.3.6.Final/documentation/manual/en-US/html_single/index.html]]> </url></link>
		<link><url><![CDATA[http://127.0.0.1:8080/hibTutorial/hibernate-release-4.3.6.Final/documentation/manual/en-US/html/index.html]]> </url></link>
		<link><url><![CDATA[http://127.0.0.1:8080/hibTutorial/hibernate-release-4.3.6.Final/documentation/javadocs/index.html]]> </url></link>
		<link><url><![CDATA[http://127.0.0.1:8080/hibTutorial/hibernate-release-4.3.6.Final/documentation/javadocs/index-all.html]]> </url></link>
		<link><url><![CDATA[http://127.0.0.1:8080/hibTutorial/hibernate-release-4.3.6.Final/documentation/devguide/en-US/html_single/index.html]]> </url></link>
		<link><url><![CDATA[http://127.0.0.1:8080/hibTutorial/hibernate-release-4.3.6.Final/documentation/devguide/en-US/html/index.html]]> </url></link>
		<link><url><![CDATA[http://127.0.0.1:8080/hibTutorial/hibernate-release-4.3.6.Final/documentation/topical/html/index.html]]> </url></link>
	</link-group>
	<link-group name="java tutorial">
		<link><url><![CDATA[http://127.0.0.1:8080/hibTutorial/tutorial/index.html]]> </url></link>
		<link><url><![CDATA[http://en.wikipedia.org/wiki/Java_(programming_language)]]> </url></link>
		<link><url><![CDATA[http://127.0.0.1:8080/jndi-1_4_2-tutorial/index.html]]> </url></link>
	</link-group>
	<link-group name="applications link group">
		<link><url><![CDATA[http://127.0.0.1:8080/hibTutorial/linkGroup.jsp]]> </url></link>
		<link><url><![CDATA[http://127.0.0.1:8080/struts2-showcase/showcase.action]]> </url></link>
		<link><url><![CDATA[http://127.0.0.1:8080/hibTutorial/displayPDFContent.jsp]]> </url></link>
		<link><url><![CDATA[http://127.0.0.1:8080/hibTutorial/pdfContentViewer.jsp]]> </url></link>
	</link-group>
	<link-group name="Experis IT/ WDC">
		<link><url><![CDATA[http://utility.experisindia.com/Apps/wdcleappsys.nsf]]> </url></link>
	</link-group>
	<link-group name="EJB">
		<link><url><![CDATA[http://docs.oracle.com/cd/E13224_01/wlw/docs103/guide/ejb/tutorial/tutEJBIntro.html]]> </url></link>
	</link-group>
	<link-group name="IT Helpdesk">
		<link><url><![CDATA[http://helpdesk.concentrix.com/admin/]]> </url></link>
		<link><url><![CDATA[http://helpdesk.concentrix.com/]]> </url></link>
	</link-group>
	<link-group name="other useful links">
		<link><url><![CDATA[http://127.0.0.1:8080/hibTutorial/activewidgets-2.6.4-trial/ActiveWidgets/examples/index.htm]]> </url></link>
	</link-group>
	<link-group name="json">
		<link><url><![CDATA[http://json.org/]]> </url></link>		
	</link-group>
	
	<link-group name="apache commons beanutils">
		<link><url><![CDATA[http://www.javaranch.com/journal/2003/07/TouringTheCommonsPart1.html]]> </url></link>
		<link><url><![CDATA[http://commons.apache.org/proper/commons-beanutils/download_beanutils.cgi]]> </url></link>
		<link><url><![CDATA[http://commons.apache.org/proper/commons-beanutils/javadocs/v1.9.2/apidocs/org/apache/commons/beanutils/package-summary.html#package_description]]> </url></link>		
	</link-group>
	
	<link-group name="jquery how to add new element and event">
		<link><url><![CDATA[http://api.jquery.com/on/]]> </url></link>
		<link><url><![CDATA[http://stackoverflow.com/questions/203198/event-binding-on-dynamically-created-elements]]> </url></link>
		<link><url><![CDATA[http://jeasyui.com/]]> </url></link>
		<link><url><![CDATA[http://127.0.0.1:8080/hibTutorial/jquery-ui-1.11.2.custom/index.html]]> </url></link>
	</link-group>
	
	<link-group name="list of tags in html">
		<link><url><![CDATA[http://htmldog.com/reference/htmltags/]]> </url></link>
		<link><url><![CDATA[http://www.tedmontgomery.com/tutorial/lists.html]]> </url></link>
		<link><url><![CDATA[http://www.w3.org/TR/html401/struct/lists.html]]> </url></link>
		<link><url><![CDATA[http://www.w3.org/TR/html401/cover.html#minitoc]]> </url></link>
	</link-group>
	
	<link-group name="List of tags in html5">
		<link><url><![CDATA[http://www.w3.org/TR/2014/REC-html5-20141028/]]> </url></link>
		<link><url><![CDATA[http://www.w3schools.com/html/html5_new_elements.asp]]> </url></link>
		<link><url><![CDATA[http://www.w3.org/TR/html-markup/elements.html]]> </url></link>
		<link><url><![CDATA[http://www.tutorialspoint.com/html5/html5_tags.htm]]> </url></link>
		<link><url><![CDATA[http://www.html-5-tutorial.com/all-html-tags.htm]]> </url></link>
		<link><url><![CDATA[http://www.w3.org/html/wg/drafts/html/master/Overview.html]]> </url></link>
	</link-group>
	
	
	<link-group name="struts 2">
		<link><url><![CDATA[http://127.0.0.1:8080/hibTutorial/struts-2.3.16.3/docs/index.html]]> </url></link>
		<link><url><![CDATA[http://127.0.0.1:8080/struts2-mailreader]]> </url></link>
	</link-group>
	
	<link-group name="struts 456278">
		<link><url><![CDATA[http://127.0.0.1:8080/hibTutorial/struts-2.3.16.3/docs/index.html]]> </url></link>
		<link><url><![CDATA[http://127.0.0.1:8080/struts2-mailreader]]> </url></link>
	</link-group>
	
	<link-group name="database management system">
		<link><url><![CDATA[http://www.studytonight.com/dbms/database-normalization.php]]> </url></link>
	</link-group>
	
	<link-group name="java course">
		<link><url><![CDATA[http://www.studytonight.com/java/overview-of-java]]> </url></link>
	</link-group>
	
	<link-group name="graph implementation in java">
		<link><url><![CDATA[http://en.wikipedia.org/wiki/Graph_(abstract_data_type)]]> </url></link>
		<link><url><![CDATA[http://www.sanfoundry.com/java-program-describe-representation-graph-using-adjacency-list/]]> </url></link>
		<link><url><![CDATA[http://algs4.cs.princeton.edu/41undirected/]]> </url></link>
		
		
	</link-group>
	
	<link-group name="DTD">
		<link><url><![CDATA[http://infohost.nmt.edu/tcc/help/pubs/dtd/index.html]]> </url></link>
	</link-group>
	
	<link-group name="English Grammar">
		<link><url><![CDATA[http://free-english-study.com/home/grammar-index.html]]> </url></link>
	</link-group>
	
	
	<link-group name="Official Application URLs">
		<link><url><![CDATA[https://hcdy.login.us2.oraclecloud.com/oam/server/obrareq.cgi?encquery%3D9CKZMzP4jdzKzudCKnK2mxVfCFy%2BkBlyq0pFvlQnZKR4mBeXPCX68Ikpxg4mUUqMxt5bHa4d65s9QmPN7v0UkSuJCKgz76ySYNq5GEUFiBJqGw277yIj8DKeVJGok3B8WtlQOudCTuw%2FrqL8PukW%2Bp6R3jbIUzpmNtkHYu2iipzgO6giudUteSA7RZC0NZitNWHhw0D7pefSZVIAp%2BtUUCegc5fXyA6vFcVobQOLLTREt%2Bll%2BzYgbfC7BjnqlpLNpsp71PfvnLQjRm%2Bsl2H6qA56WiNd5wl7uvj0H4KDFvlly6FxI%2BARKiWNWTblYMhPvv94o40nHDZoErQIoh9yElpOTQi4OXSWGMxrtvli5iW%2B2WMijYIXL6nyWvH8GREvVNbqMeFZCQsFmB7HFqEniUyg2mt05ciWznEuEhVB5ucfLhi02GYRESoqYSN87y23luaQC5ojk%2FRjZ3jwy9tkVlEGB29RkQqH2jntnKnGeL7tIa3J%2Fr6KHzVEetUiLir4%20agentid%3DOraFusionApp_11AG%20ver%3D1%20crmethod%3D2]]> </url></link>
		
		<link><url><![CDATA[https://116.90.243.58/OneTouch/]]> </url></link>
		
		<link><url><![CDATA[https://hcdy.hcm.us2.oraclecloud.com/hcmCore/faces/HcmFusionHome]]> </url></link>
		
		<link><url><![CDATA[https://116.90.243.15/ebucks/]]> </url></link>
		
		<link><url><![CDATA[https://helpdesk.concentrix.com/survey/helpdesk_reporting.php?dfrom=2015-02-26&dto=2015-02-27&submit=Generate&site=150&staff=0&status=any&escalated=0&scrubbed=all&keyword=&requestor=]]> </url></link>
		
	</link-group>
	
	<link-group name="XML and DTD syntax">
		<link><url><![CDATA[http://www.linuxfromscratch.org/alfs/view/dtd/alfs_dtd/xml_dtd-syntax.html]]> </url></link>
		<link><url><![CDATA[http://oak.cs.ucla.edu/cs144/reference/DTD.html]]> </url></link>
		<link><url><![CDATA[http://www.rpbourret.com/xml/xmldtd.htm]]> </url></link>
	</link-group>
	
	<link-group name="xml schema validation java">
		<link><url><![CDATA[http://docs.oracle.com/javase/tutorial/jaxp/dom/validating.html]]> </url></link>
		<link><url><![CDATA[http://docs.oracle.com/javase/7/docs/api/javax/xml/validation/package-summary.html]]> </url></link>
		<link><url><![CDATA[http://www.journaldev.com/895/how-to-validate-xml-against-xsd-in-java]]> </url></link>
		<link><url><![CDATA[http://www.ibm.com/developerworks/library/x-javaxmlvalidapi/]]> </url></link>
		<link><url><![CDATA[http://stackoverflow.com/questions/17107596/xml-schema-validation-using-java-code]]> </url></link>
		<link><url><![CDATA[http://www.w3.org/TR/xmlschema-0/]]> </url></link>
		<link><url><![CDATA[http://www.edankert.com/validate.html]]> </url></link>
	</link-group>
	
	<link-group name="automate deployment of war file in websphere">
		<link><url><![CDATA[http://www.ibm.com/developerworks/library/mo-worklight-deploy-raf/sidefile-fig1.html]]> </url></link>
		<link><url><![CDATA[https://www.packtpub.com/books/content/deploying-your-applications-websphere-application-server-70-part-1]]> </url></link>
	</link-group>
	
	
	<link-group name="Installing the Eclipse Plugin for Android">
		<link><url><![CDATA[http://developer.android.com/sdk/installing/installing-adt.html]]> </url></link>
		<link><url><![CDATA[http://developer.android.com/training/index.html]]> </url></link>
	</link-group>
	
	<link-group name="Deploying And Managing an application using ws_ant in IBM WebSphere Application Server">
		<link><url><![CDATA[http://www.techpaste.com/2012/02/07/deploying-managing-application-ws_ant-ibm-websphere-application-server/]]> </url></link>
		<link><url><![CDATA[http://stackoverflow.com/questions/3117785/using-ant-to-deploy-ear-to-remote-websphere-application-server]]> </url></link>
